### PR TITLE
Ability to add agent url on config screen

### PR DESCRIPTION
**Pull request by HunnySajid**
https://github.com/WebOfTrust/signify-browser-extension/issues/91

### CODE REVIEW

**Comment by HunnySajid** [comment]
@rodolfomiranda @2byrds 
The agent URL is added to the config screen. The user can not proceed without adding the vendor and agent URLs. 
The default Keria theme is also set at `src/config/vendor.json` 

https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/c7215a54-c244-4874-b140-fad2ebd3debe

**Comment by 2byrds** [comment]
@HunnySajid if they provide the vendor URL it should pre-populate the keria URL in most cases. So I think the keria URL should only be available if they have no vendor URL or if the vendor URL JSON does not provide a keria agent. Thoughts @rodolfomiranda ?

**Comment by rodolfomiranda** [comment]
> @HunnySajid if they provide the vendor URL it should pre-populate the keria URL in most cases? So I think the keria URL should only be available if they have no vendor URL or if the vendor URL JSON does not provide a keria agent. Thoughts @rodolfomiranda ?

agree. The normal case is to enter the vendor URL, but we should provide an option for users that use own KERIA instances. A small link with that option may work

**Comment by 2byrds** [comment]
> > @HunnySajid if they provide the vendor URL it should pre-populate the keria URL in most cases? So I think the keria URL should only be available if they have no vendor URL or if the vendor URL JSON does not provide a keria agent. Thoughts @rodolfomiranda ?
> 
> agree. The normal case is to enter the vendor URL, but we should provide an option for users that use own KERIA instances. A small link with that option may work

That sounds good. I think if the vendor URL gives you a keria agent then it should be filled in. And you see it IF YOU click the link. If the vendor URL doesn't supply it, then the link automatically opens and the user has to fill it in.

**Comment by HunnySajid** [comment]
> > @HunnySajid if they provide the vendor URL it should pre-populate the keria URL in most cases? So I think the keria URL should only be available if they have no vendor URL or if the vendor URL JSON does not provide a keria agent. Thoughts @rodolfomiranda ?
> 
> agree. The normal case is to enter the vendor URL, but we should provide an option for users that use own KERIA instances. A small link with that option may work

@rodolfomiranda
Even in that case, user needs to load vendor JSON otherwise they can not proceed.
Let's put an array of string agentUrls.

**Comment by HunnySajid** [comment]
@rodolfomiranda @2byrds 

In the previous flow, it was cumbersome for the user to type/paste multiple URLs. e.g vendor_url then agent_url.
Also, it was not seamless as the popup was getting close between copy pasting.

I have updated the flow, now agentUrls are a part of vendor JSON as an array of string.

`"agentUrls": ["https://keria-dev.rootsid.cloud/admin", "https://keria-dev.rootsid.cloud/fakeone"]` 

If vendor json does not have **agentUrls**, the extension throws an error

### JSON loaded without agentUrls

https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/473dd2e2-70de-4c78-99d5-a7229793659f

If vendor JSON has agentUrls then the first URL is selected and flow continues, user can change the URL from dropdown later on:

### JSON loaded with agentUrls



https://github.com/WebOfTrust/signify-browser-extension/assets/19255438/ae9eeb87-e5d0-48ba-8e0f-32f8be275dbf

Let me know how it looks.

**Comment by 2byrds** [comment]
@HunnySajid thank you for posting a look. Does the vendor URL have to have an agent URL? I don't think that should be mandatory, so no error if it's missing. Instead if there is no agent URL the UI makes the user fill it in. Also the user should have the option to fill it in even if the vendor does provide it, as u showed.

**Comment by rodolfomiranda** [comment]
What's the case for a vendor URL to not have a agent URL? also, what's the purpose of having multiple agent URLs in the json?

**Comment by HunnySajid** [comment]
> What's the case for a vendor URL to not have a agent URL? also, what's the purpose of having multiple agent URLs in the json?

 **What's the case for a vendor URL to not have a agent URL?**
 The assumption is vendor would provide an agentUrl or a list of agentUrls to developers. I saw Lance's comment that it is not mandatory for vendors to provide agentUrl to developers. The devs can connect with any agent so they can fill in the agentUrl field as well.
 
**what's the purpose of having multiple agent URLs in the json**
The assumption was that vendors would provide a list of agentUrls and developer can connect with any of the listed agents.

Now, I am making following changes:
- remove agentsUrl from JSON and use one optional field named agentUrl. 
- instead of dropdown for agentUrl selection, use a text field which could be edited by user.

**Comment by rodolfomiranda** [comment]
I imagine that the vendor URL will be use for real users that were onboarded previously by the vendior. Only devs or expert users may need to use a custom agentURL, and vendor theming shouldn't be needed.

**Comment by HunnySajid** [comment]
@rodolfomiranda i have made updates based on the conversation. Please review

**Comment by HunnySajid** [comment]
Video for latest changes:
https://www.loom.com/share/3216332fce6945f797e21290d2efa624?sid=1d7cee04-5c99-48dc-ae7e-d674b7423774

**Comment by HunnySajid** [comment]
Demo review changes: https://github.com/WebOfTrust/signify-browser-extension/issues/93

**Review by 2byrds — APPROVED** [review]
LGTM

**Pull request merged**
