### PR TITLE
Feat/cred chain

### PR DESCRIPTION
**Pull request by HunnySajid**
https://github.com/WebOfTrust/signify-browser-extension/issues/210

### CODE REVIEW

**Review by 2byrds — APPROVED** [review]

**Comment by 2byrds** [comment]
@HunnySajid can u add some screenshots?

**Comment by HunnySajid** [comment]
**Credential View Changes**
In the default or selection view, only those credentials that have issueName associated with them are displayed.

Screenshot 2024-10-29 at 12 05 50 AM

In default mode, each credential that have a chain displays an explore component, that expands and displays credential chain
Screenshot 2024-10-29 at 12 06 04 AM

Upon clicking a node in chain, it expands and shows its children if exist.

Upon clicking on **folder icon** on right side of a credential node, it takes user to that particular credential with its path displayed in breadcrumb.
Screenshot 2024-10-29 at 12 06 19 AM

Ideally, I wanted to make breadcrumb navigatable so that user can click on a breadcrumb and move to that credential but there was a challenge to maintain all user journey through this navigation. 
For now, there is a back button in front of breadcrumb that takes user back to the original / default state of credential view.

Video Illustration


https://github.com/user-attachments/assets/127f916e-5206-4137-b5cb-2a271b0b029d

@2byrds let me know your feedback

**Comment by HunnySajid** [comment]
@2byrds as in current example we are showing edges to root connection,
I was discussing with Aidar for a feature where we can show all of the credential chain from root to edges.

The idea is as follows:
- Show an icon to explore along with the **Credentials** Heading
- Once user clicks on it, it opens a separate extension page in browser eg extension_id/credential_chain
- That page displays a connection tree from root credential to different edges like a map

**Comment by HunnySajid** [comment]
> The Idea seems nice! @HunnySajid just a small sugesstion, you can also add a drop down menu icon near to the explore and credential chain so end users can know something is there and click on it otherwise first time users won't be able to there is a chain.

Thanks @Jayharwani for the suggestion, I added a ">" in collapsed state of a node

https://github.com/user-attachments/assets/bce8778e-15bb-4272-8b45-3fad2b88e1d4

**Comment by Jayharwani** [comment]
> > The Idea seems nice! @HunnySajid just a small sugesstion, you can also add a drop down menu icon near to the explore and credential chain so end users can know something is there and click on it otherwise first time users won't be able to there is a chain.
> 
> Thanks @Jayharwani for the suggestion, I added a ">" in collapsed state of a node
> 
>  Screen.Recording.2024-10-29.at.6.25.43.PM.mov

Perfect!

**Pull request merged**
